// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCBA.DCL.Data;

#nullable disable

namespace NCBA.DCL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106195547_comment")]
    partial class comment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NCBA.DCL.Models.Approver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DeferralId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeferralId");

                    b.ToTable("Approvers");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Checklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedToCoCheckerId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AssignedToRMId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DclNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DocumentsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("LoanType")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToCoCheckerId");

                    b.HasIndex("AssignedToRMId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CustomerId");

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ChecklistLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("UserId");

                    b.ToTable("ChecklistLogs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.CoCreatorFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("CoCreatorFiles");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Deferral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BusinessName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<int>("CurrentApproverIndex")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("DeferralNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoanType")
                        .HasColumnType("longtext");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeferralNumber")
                        .IsUnique();

                    b.ToTable("Deferrals");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DeferralDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DeferralId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeferralId");

                    b.HasIndex("UploadedById");

                    b.ToTable("DeferralDocuments");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CheckerComment")
                        .HasColumnType("longtext");

                    b.Property<string>("CheckerStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorComment")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatorStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("DeferralReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("RmComment")
                        .HasColumnType("longtext");

                    b.Property<string>("RmStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DocumentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.ToTable("DocumentCategories");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DeferralId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Headroom")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Sanctioned")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeferralId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<bool>("Read")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NCBA.DCL.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RmId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RmId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NCBA.DCL.Models.UserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PerformedByEmail")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("TargetEmail")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.HasIndex("TargetUserId");

                    b.ToTable("UserLogs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Approver", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Deferral", "Deferral")
                        .WithMany("Approvers")
                        .HasForeignKey("DeferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deferral");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Checklist", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "AssignedToCoChecker")
                        .WithMany("AssignedAsCoChecker")
                        .HasForeignKey("AssignedToCoCheckerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "AssignedToRM")
                        .WithMany("AssignedAsRM")
                        .HasForeignKey("AssignedToRMId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "CreatedBy")
                        .WithMany("CreatedChecklists")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToCoChecker");

                    b.Navigation("AssignedToRM");

                    b.Navigation("CreatedBy");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NCBA.DCL.Models.ChecklistLog", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Checklist", "Checklist")
                        .WithMany("Logs")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Checklist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.CoCreatorFile", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Document", "Document")
                        .WithMany("CoCreatorFiles")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Deferral", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "CreatedBy")
                        .WithMany("CreatedDeferrals")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DeferralDocument", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Deferral", "Deferral")
                        .WithMany("Documents")
                        .HasForeignKey("DeferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NCBA.DCL.Models.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Deferral");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Document", b =>
                {
                    b.HasOne("NCBA.DCL.Models.DocumentCategory", "DocumentCategory")
                        .WithMany("DocList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentCategory");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DocumentCategory", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Checklist", "Checklist")
                        .WithMany("Documents")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Facility", b =>
                {
                    b.HasOne("NCBA.DCL.Models.Deferral", "Deferral")
                        .WithMany("Facilities")
                        .HasForeignKey("DeferralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deferral");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Notification", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("NCBA.DCL.Models.UserLog", b =>
                {
                    b.HasOne("NCBA.DCL.Models.User", "PerformedBy")
                        .WithMany("PerformedByLogs")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NCBA.DCL.Models.User", "TargetUser")
                        .WithMany("TargetUserLogs")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerformedBy");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Checklist", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Deferral", b =>
                {
                    b.Navigation("Approvers");

                    b.Navigation("Documents");

                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("NCBA.DCL.Models.Document", b =>
                {
                    b.Navigation("CoCreatorFiles");
                });

            modelBuilder.Entity("NCBA.DCL.Models.DocumentCategory", b =>
                {
                    b.Navigation("DocList");
                });

            modelBuilder.Entity("NCBA.DCL.Models.User", b =>
                {
                    b.Navigation("AssignedAsCoChecker");

                    b.Navigation("AssignedAsRM");

                    b.Navigation("CreatedChecklists");

                    b.Navigation("CreatedDeferrals");

                    b.Navigation("Notifications");

                    b.Navigation("PerformedByLogs");

                    b.Navigation("TargetUserLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
